# Copyright 2026 Jordan Castro <jordan@grupojvm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
#
[package]
name = "pixelscript"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
mlua = { version = "0.11", features = ["lua54", "vendored", "send"], optional = true }
anyhow = "1.0.100"
# rustpython-vm = { version = "0.4.0", default-features = false, features = ["compiler", "codegen", "freeze-stdlib"], optional = true }
# rustpython-compiler = {version = "0.4.0", optional = true}
parking_lot = "0.12.5"
thread_local = "1.1.9"

[build-dependencies]
cbindgen = "0.29.2"
cc = "1.2.52"
bindgen = "0.72.1"

[features]
# Default includes all languages.
default = ["lua", "python"]
# Include LUA scripting.
lua = ["dep:mlua"]
# Include Python scripting. Via pocketpy
python = []
# Include Python scripting. via rustpython
# rustpython = ["dep:rustpython-vm", "dep:rustpython-compiler"]

include-core = []
all = ["lua", "python"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"